language: cpp
cache: ccache

notifications:
  email:
    - amarburg@apl.washington.edu

# Per-OS configuration
matrix:
  env:
    - BUILD_TYPE=release
#    - BUILD_TYPE=Debug
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install rake ; fi
  - rake dependencies:travis:$TRAVIS_OS_NAME

script: rake debug:test release:test
